### ISSUE TITLE
Error when creating Win2016Core_G2.vhdx or Win2016NanoHV_G2.vhdx

### ISSUE THREAD

**Issue by mikumich** [microsoft/MSLab#405]
Requirements (what I have):
1) WS2016 VL ISO: SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.ISO
2) \WSLab\ParentDisks\1607\2020-11:
- windows10.0-kb4576750-x64_c4e0b5e0f0835db971a40058aa17ae9a0d2f1e2a.msu
- windows10.0-kb4586830-x64_30c6444c0319caa72579a4c59e2e93d756dc9f21.msu
downloaded with: \WSLab\ParentDisks\DownloadLatestCUs.ps1

Then I run:
\WSLab\ParentDisks\CreateParentDisk.ps1 for Windows Server 2016 DataCenter without GUI
and got this:

> Please select ISO image
> 
> GAC    Version        Location                                                                                          ---    -------        --------                                                                                          True   v4.0.30319     C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089... File D:\ISOs\Windows Server\Windows Server 2016 VL\SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.ISO selected                                                                                                          Please select msu packages you want to add to image. Click cancel if you don't want any.                                True   v4.0.30319     C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089... Following patches selected:                                                                                                      V:\WSLab\ParentDisks\1607\2020-11\windows10.0-kb4576750-x64_c4e0b5e0f0835db971a40058aa17ae9a0d2f1e2a.msu                V:\WSLab\ParentDisks\1607\2020-11\windows10.0-kb4586830-x64_30c6444c0319caa72579a4c59e2e93d756dc9f21.msu
> Server 2016 ISO Selected. Do you want to build NanoServer? Y/N: N
> Please type VHD name (if nothing specified, Win2016Core_G2.vhdx is used:
> Please type size of the Image in GB. If nothing specified, 60 is used:
> 
> Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
> Copyright (C) Microsoft Corporation.  All rights reserved.
> Version 10.0.14278.1000.amd64fre.rs1_es_media.160201-1707
> 
> INFO   : Looking for the requested Windows image in the WIM file
> INFO   : Creating sparse disk...
> INFO   : Mounting VHDX...
> INFO   : Initializing disk...
> INFO   : Creating EFI system partition...
> INFO   : Formatting system volume...
> INFO   : Setting system partition as ESP...
> INFO   : Creating MSR partition...
> INFO   : Creating windows partition...
> INFO   : Formatting windows volume...
> INFO   : Windows path (H:) has been assigned.
> INFO   : Windows path (H:) took 1 attempts to be assigned.
> INFO   : System volume location: G:
> INFO   : Applying image to VHDX. This could take a while...
> INFO   : Image was applied successfully.
> INFO   : Making image bootable...
> INFO   : Drive is bootable.  Cleaning up...
> INFO   : Adding Windows Packages to the Image
> INFO   : Package path: V:\WSLab\ParentDisks\1607\2020-11\windows10.0-kb4576750-x64_c4e0b5e0f0835db971a40058aa17ae9a0d2f1e2a.msu
> INFO   : Package path: V:\WSLab\ParentDisks\1607\2020-11\windows10.0-kb4586830-x64_30c6444c0319caa72579a4c59e2e93d756dc9f21.msu
> WARNING: Failed to add package
> V:\WSLab\ParentDisks\1607\2020-11\windows10.0-kb4586830-x64_30c6444c0319caa72579a4c59e2e93d756dc9f21.msu
> WARNING: Add-WindowsPackage failed. Error code = 0x800f081f
> ERROR  : An error occurred applying the Unattend.xml file from the .msu package.
> For more information, review the log file.
> 
> INFO   : Log folder is C:\Users\{user}\AppData\Local\Temp\Convert-WindowsImage\ed7b0cc5-d9dc-45f1-b573-757a7af47f36
> INFO   : Done.
> Dismounting ISO Image
> 
> Attached          : False
> BlockSize         : 0
> DevicePath        :
> FileSize          : 6003804160
> ImagePath         : D:\ISOs\Windows Server\Windows Server 2016 VL\SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_
>                     STD_MLF_X21-70526.ISO
> LogicalSectorSize : 2048
> Number            :
> Size              : 6003804160
> StorageType       : 1
> PSComputerName    :
> 
> Job Done. Press enter to continue...

In \WSLab\ParentDisks i have: ed7b0cc5-d9dc-45f1-b573-757a7af47f36.vhdx (I've deleted it manually)

Without CUs it's ending successfully
Same scenario for Win2016NanoHV_G2.vhdx

**Comment by jsporbert** [comment]
Issue creating Parent Disk when script is run directly under root path.
If I run the Create_ParentDisk PS script and the script is located at the root of a disk, it will failed with error:

Cannot bind argument to parameter 'Path' because it is an empty string.

**Comment by jaromirk** [comment]
I folks, sorry for late reply. The CU was not applied because you should also apply SSU (Servicing Stack Update) I think. Give it a try - DownloadLatestCU.ps1 will do the job for downloading both SSU and CUs. @jsporbert I'll keep your issue in mind and detect it (and if root, it will not continue and let you know)
