### ISSUE TITLE
query regarding "incremental Backup"

### ISSUE THREAD

**Issue by n-mam** [microsoft/MSLab#409]
Hi 

In the section titled "Perform incremental backup" in the readme.md for "S2D and Resilient Change Tracking" we have a comment stating "Exports differential backup of the machine" . However, the "lastreferencepoint" variable I believe references the "latest" reference point, thus making it an incremental backup. Would that be correct ? Is "lastreferencepoint" chronologically the first or the latest reference point ?

![image](https://user-images.githubusercontent.com/17683324/100825368-dc821100-347d-11eb-8e8c-92c044110fce.png)

**Comment by jaromirk** [comment]
It is latest - I mean the checkpoint (increment) that was created as the last one (I think :). Did you actually run scenario? I would have to spin it to give you 100 legit answer. @machv for visibility

**Comment by n-mam** [comment]
Yes, I did execute this block after posting the question and indeed it does return the latest checkpoint id. I believe, that makes the current backup incremental with respect to the most recent available reference point. I am wondering... it is not like we'd take a checkpoint (for incremental) immediately after taking a full backup.. that usually would happen at a reasonably forward point in time. With that, if a reference point gets created by some other workflow then our incremental backup chain would be broken since we'd be missing the changed blocks for earlier reference points.. Like, the backup at time tn+1 should ideally refer to the reference point created as part of backup B3 but instead it would unconditionally export the incremental blocks across the B6 reference point and the Tn+1 backup checkpoint. The resulting avhdx at Tn+1 wont have changed data between the point in time T3 and Tn. I think we should be preserving each of "our" reference point IDs as part of the last incremental backup, query that during the subsequent incremental and then use that. 

On the other hand, if for every backup (except the first full) if we would have given the reference point of the first full backup then all such backups (after the first full) would be differential with respect to the first full.. That's my usual understanding. Are you aware of any doc from MSFT which highlights the differential aspect ?

![image](https://user-images.githubusercontent.com/17683324/100896377-901dec00-34e4-11eb-9ca8-ce0dc3450c5e.png)

**Comment by jaromirk** [comment]
Well, feel free to PR. I just made all up - just to demonstrate that there are also increments possible :).

**Comment by jaromirk** [comment]
@machv do you have an opinion on this?

**Comment by jaromirk** [comment]
closing as I dont have an answer for this
