### ISSUE TITLE
Install latest CU for existing VMs / Images in WSLab 

### ISSUE THREAD

**Issue by DenBir** [microsoft/MSLab#430]
Hi, great tool!

I use WSLab for several environments but the images and VMs have always the patch status for the initial phase. 

It is possible to update all existing VMs / Images in the WSLab environment? I find only the script to download the latest CU and install this in the initial phase (create image) on step 2.

Possible Solution:
Create a further script to update the images and / or the associated VMs.

**Comment by jaromirk** [comment]
Yup, I was thinking the same. I'll do it :). Should be relatively easy.

**Comment by jaromirk** [comment]
I added this script https://github.com/microsoft/WSLab/blob/dev/Tools/PatchParentDisks.ps1 ... it will be downloaded with 1_prereqs.ps1. Please give it a try! As usual, right-click and run with powershell...

**Comment by jaromirk** [comment]
Tested, works :). Closing.

**Comment by DenBir** [comment]
Great! Thanks!

**Comment by jaromirk** [comment]
You're welcome. Let me know how it works!
