### ISSUE TITLE
Row 249 I removed the "=" , and error can be overcome

### ISSUE THREAD

**Issue by dafoyiming** [microsoft/MSLab#438]
Cannot process argument transformation on parameter 'controlplaneVmSize'. Cannot convert value "=" to type "VmSize". Error: "Unable to match the identifier name = to a valid 
enumerator name. Specify one of the following enumerator names and try again:
Default, Standard_A2_v2, Standard_A4_v2, Standard_D2s_v3, Standard_D4s_v3, Standard_D8s_v3, Standard_D16s_v3, Standard_D32s_v3, Standard_DS2_v2, Standard_DS3_v2, Standard_DS4_v2, 
Standard_DS5_v2, Standard_DS13_v2, Standard_K8S_v1, Standard_K8S2_v1, Standard_K8S3_v1, Standard_NK6, Standard_NV6, Standard_NV12"
    + CategoryInfo          : InvalidData: (:) [Set-AksHciConfig], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-AksHciConfig
    + PSComputerName        : AzSHCI1

**Comment by jaromirk** [comment]
Thank you! Just fixed it... Sorry!
