### ISSUE TITLE
Fails to install  Azure Stack HCI RSAT Tools

### ISSUE THREAD

**Issue by gopoking** [microsoft/MSLab#444]
I'm following the scenario for Azure Stack HCI and Kubernetes. Using the scenario script, it fails to install  Azure Stack HCI RSAT Tools.

`Install-WindowsFeature : ArgumentNotValid: The role, role service, or feature name is not
valid: 'RSAT-Azure-Stack-HCI'. The name was not found.
At line:1 char:5
+     Install-WindowsFeature -Name RSAT-Azure-Stack-HCI
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (RSAT-Azure-Stack-HCI:String) [Install-Windo
   wsFeature], Exception
    + FullyQualifiedErrorId : NameDoesNotExist,Microsoft.Windows.ServerManager.Commands.Add
   WindowsFeatureCommand`

**Comment by jaromirk** [comment]
Hi, sorry for late reply! I reviewed to scenario and all worked well for me. It's invoking this to servers that needs to be Azure Stack HCI OS.
