### ISSUE TITLE
Server parent disk Win2022Core_G2.vhdx not found

### ISSUE THREAD

**Issue by treuwark** [microsoft/MSLab#456]
Got that message while deploying phase

	 Restarting service RemoteAccess...
Creating DSC config to configure DC as pull server
Processing $LabConfig.VMs, creating VMs
Creating VM S2D1
	 Looking for Parent Disk
Server parent disk Win2022Core_G2.vhdx not found.
Press enter to continue ...
**********************
Ende der Windows PowerShell-Aufzeichnung

Use Windows Server 2019 ISO with CU patched.
What´s the trick ?

**Comment by zotyka** [comment]
I have the same problem.. what is the solution? Pls. help!
