### ISSUE TITLE
Many hard coded credentials

### ISSUE THREAD

**Issue by DenBir** [microsoft/MSLab#467]
Hi Jaromir, great project. I love it!

I try to use my own credentials for the whole lab environment and I stuck on many times that are the credentials are hard coded.

e.g. dedploy VMFleet
![image](https://user-images.githubusercontent.com/42352926/136923658-ccead739-f9c4-4082-8532-7dae65f0ead9.png)

It is possible to set in the first script your own credentials and this works for the whole lab environment?

**Comment by jaromirk** [comment]
Hi! Got it! Btw. forget deployVMFleet script. I already removed it in new versions. Take a look here https://github.com/microsoft/MSLab/tree/master/Scenarios/AzSHCI%20and%20VMFleet - it's adjusted for new VMFleet. And also there is new tool to create VMFleet image in tools (downloaded with prereqs) https://github.com/microsoft/MSLab/blob/master/Tools/CreateVMFleetDisk.ps1

**Comment by jaromirk** [comment]
Teams call? Ping me at jaromir.kaspar@dell.com

**Comment by jaromirk** [comment]
btw. please forget that old script. Create vmfleet image with CreateFMFleetDisk.ps1. It will ask for VHDX, so provide one from parent disks (windows server core). It will also ask for password. This needs to be the same as you later provide as -AdminPass ... -Admin will be always Administrator ... -ConnectUser and -ConnectPass are admin credentials in plaintext to be able to connect to collect file share.
