### ISSUE TITLE
Scenario.ps1 typo

### ISSUE THREAD

**Issue by devops-app** [microsoft/MSLab#475]
https://github.com/microsoft/MSLab/blob/master/Scenarios/S2D%20and%20Cloud%20Services%20Onboarding/scenario.ps1

Line 78:     $context | Out-GridView -OutpuMode Single | Set-AzContext

Please update to $context | Out-GridView -**OutputMode** Single | Set-AzContext

**Comment by jaromirk** [comment]
Thank you! I apparently copied it, so it was in multiple scenarios :)
