### ISSUE TITLE
Does not respect config and deployment fails with custom domain

### ISSUE THREAD

**Issue by donchia** [microsoft/MSLab#478]
Trying to specify custom DomainNetbiosName and DomainName in the $LabConfig=@ deployment fails

**Comment by jaromirk** [comment]
Hey donchia, can you post your labconfig here? I would give it a try. THX!

**Comment by donchia** [comment]
It does work when I change domain later with "rendom" on DC from corp.contoso.com to custom.com, but I am not able to setup initial DC with custom domain config - deployment stuck in the middle.

$LabConfig=@{ DomainAdminName='LabAdmin'; AdminPassword='LS1setup!'; Prefix = 'B19Lab-' ; DomainName='custom.com' ; DomainNetbiosName='CUSTOM'; DCEdition='4'; Internet=$true ; SwitchName='b19LabSwitch' ; AdditionalNetworksConfig=@(); VMs=@()}

$LABConfig.VMs += @{ VMName = 'W10_1' ; Configuration = 'Simple'   ; ParentVHD = 'Win10_G2.vhdx'    ; MemoryStartupBytes= 4GB ; AddToolsVHD=$True ; DisableWCF=$True}

**Comment by jaromirk** [comment]
Just tried it... worked like a charm...  I'm using powershell 5
![image](https://user-images.githubusercontent.com/9829838/148545350-1b4a3b35-694d-4cb1-a52d-dade65698741.png)
