### ISSUE TITLE
AzSHCI and MDT - Credentials

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [microsoft/MSLab#480]
Credentials are static in the scenario script.
see https://github.com/microsoft/MSLab/blob/master/Scenarios/AzSHCI%20and%20MDT/Scenario.ps1#L81

What would be the best way to read the Labconfig, instead of assuming credentials and stuff failing?

**Comment by jaromirk** [comment]
Done

**Comment by jaromirk** [comment]
it is provided in variables...
