### ISSUE TITLE
Scenario CA

### ISSUE THREAD

**Issue by Mrkuff** [microsoft/MSLab#491]
I got this error of CA configuration for Mime

PS C:\Windows\system32> Invoke-Command -ComputerName ca -ScriptBlock {
    & $Env:WinDir\system32\inetsrv\appcmd.exe set config /section:staticContent /-"[fileExtension='.pem']"
    & $Env:WinDir\system32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.pem',mimeType='text/plain']"
}
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.webServer/staticContent" for "MACHINE/WEBROOT/APPHOST" at configurati
on commit path "MACHINE/WEBROOT/APPHOST"

**Comment by jaromirk** [comment]
yeah, I think this is OK. Removing the extension ("/-"[fileExtension='.pem']") that does not exist will cause this error (and yes, it did not exist). It's because I did reuse the linked guide 1:1.
