### ISSUE TITLE
Guest VM clustered option

### ISSUE THREAD

**Issue by DillyBabu** [microsoft/MSLab#494]
Hi,
While I am deploying a new VM using admincenter, the new VM is created as 'Clustered'. But, when trying from powershell I am only able to select a node and deploy a VM in it. I am using the following command.
New-VM -ComputerName "node01" `
       -Name "guestvm1" `
       -MemoryStartupBytes 4GB `
       -VHDPath "C:\Clusterstorage\Volume01\VHD's\guestvm1.vhdx" `
       -Path "C:\ClusterStorage\Volume02\VMS\" `
       -Generation 2 `
       -SwitchName "Mgmt_vmSwitch" `
       -ErrorAction Stop
  Instead of "node01" in the above command, I tried with cluster name "cluster1". It doesn't allow me to login.
![guestvm clustered](https://user-images.githubusercontent.com/16417357/154086594-1a1ab7f7-f71a-496b-8563-219b47ac96a9.JPG)

Is this because of  no power shell option available in the cluster manager tools section? Kindly guide me. Thanks!

**Comment by jaromirk** [comment]
Yeah, after creating VM you need to add it as clustered resource 

```PowerShell
    #add VM as clustered role
    Add-ClusterVirtualMachineRole -VMName $VM.VMName -Cluster $ClusterName
```

More info here https://github.com/microsoft/MSLab/tree/master/Scenarios/S2D%20and%20Bulk%20VM%20creation
