### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Mrkuff** [microsoft/MSLab#496]
Typo on link "TPM Key attestation docs" from https://github.com/microsoft/MSLab/blob/master/Scenarios/Certification%20Authority/readme.md
Linking to :
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation%60

Instead of
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation

**Comment by jaromirk** [comment]
Fixed...
