### ISSUE TITLE
Problem with LabConfig Domain Name

### ISSUE THREAD

**Issue by Mrkuff** [microsoft/MSLab#498]
If I'm adding DomainNetbiosName="Test"; DomainName="Test.Local"; to the LabConfig , then the "Waiting for Active Directory on $($DC.name) to be Started" never stop…
Exemple from Certificate Authority:

$LabConfig=@{ DomainAdminName='LabAdmin'; AdminPassword='LS1setup!'; Prefix = 'WSLab2022-'; SwitchName = 'LabSwitch'; DCEdition='4' ; DomainNetbiosName="Test"; DomainName="Test.Local"; Internet=$true ;AdditionalNetworksConfig=@(); VMs=@()}

$LabConfig.VMs += @{ VMName = 'CA'    ; Configuration = 'Simple' ; ParentVHD = 'Win2022Core_G2.vhdx' ; MemoryStartupBytes= 1GB ; MemoryMinimumBytes=1GB ; vTPM=$True }

$LabConfig.VMs += @{ VMName = 'Server1'     ; Configuration = 'Simple'; ParentVHD = 'Win2022Core_G2.vhdx' ; MemoryStartupBytes= 512MB ; vTPM=$True }
$LabConfig.VMs += @{ VMName = 'Server2'     ; Configuration = 'Simple'; ParentVHD = 'Win2022Core_G2.vhdx' ; MemoryStartupBytes= 512MB ; vTPM=$True }
$LabConfig.VMs += @{ VMName = 'Server3'     ; Configuration = 'Simple'; ParentVHD = 'Win2022Core_G2.vhdx' ; MemoryStartupBytes= 512MB ; vTPM=$True } 

Is there a check for the domain name? Is .Local permitted?

![image](https://user-images.githubusercontent.com/15654765/154136556-3ee3d23a-1455-46b4-a99d-27b9cd4e3a4a.png)

Thx

**Comment by Mrkuff** [comment]
I don't know whats wrong ..

$LabConfig=@{ DomainAdminName='LabAdmin'; AdminPassword='LS1setup!'; Prefix = 'WSLab2022-'; SwitchName = 'LabSwitch'; DCEdition='4' ; DomainNetbiosName="Test"; DomainName="Test.Local"; Internet=$true ;AdditionalNetworksConfig=@(); VMs=@()}


$DN=$null
    $LabConfig.DomainName.Split(".") | ForEach-Object {
        $DN+="DC=$_,"
    }
    $LabConfig.DN=$DN.TrimEnd(",")

    $DC=get-vm -Name ($labconfig.prefix+"DC")
    
    #Credentials for Session
        $username = "$($Labconfig.DomainNetbiosName)\Administrator"
        $password = $LabConfig.AdminPassword
        $secstr = New-Object -TypeName System.Security.SecureString
        $password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
        $cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr

    
    $test=Invoke-Command -VMGuid $DC.id -Credential $cred -ArgumentList $Labconfig -ErrorAction Ignore -ScriptBlock {
                param($labconfig);
                Get-ADComputer -Filter * -SearchBase "$($LabConfig.DN)" -ErrorAction Ignore
                }

**Comment by Mrkuff** [comment]
When i'm removing the -ErrorAction Ignore from Invoke-Command, I'm getting a "The credential is invalid"

![image](https://user-images.githubusercontent.com/15654765/154144569-398c0743-c562-4879-b8f3-ec05cd3cb48c.png)

So... we got a wrong password init ?

**Comment by Mrkuff** [comment]
When I'm loging into the DC and run the Get-Adcomputer I'm getting this! 

![image](https://user-images.githubusercontent.com/15654765/154177655-2a120afc-fda3-460f-bdb1-1f8a16b72d5b.png)

**Comment by jaromirk** [comment]
You can create your domain (specify your own domain) only during 2_createparentdisks.ps1 phase. During deploy.ps1 is domain already created and DC is only imported (to speed up process...

**Comment by Mrkuff** [comment]
oh.. What the tag "DomainNetbiosName="Test"; DomainName="Test.Local" do in deploy.ps1 then?

**Comment by jaromirk** [comment]
If it's different from what was specified in 2_createparentdisks.ps1, it will break things because domain is used to specify credentials that tests if DC is up and running before additional VMs are created... So that's the reason its broken for you 😉.
