### ISSUE TITLE
DownloadLatestCU is not working

### ISSUE THREAD

**Issue by DenBir** [microsoft/MSLab#507]
Hi @jaromirk,

your script to download the latest CU https://github.com/microsoft/MSLab/blob/master/Tools/DownloadLatestCUs.ps1 is not working.

I can choose from GridView the right version and then I got this message in a loop:
Multiple files exist for this update. Enter the Id of the file to download or 'A' to download all files.: A

![image](https://user-images.githubusercontent.com/42352926/165458663-c88d9999-6848-4599-9121-18dc1d4bd511.png)

It would be great if this worked again ;-).

**Comment by jaromirk** [comment]
THX, will take a look!

**Comment by jaromirk** [comment]
Hmm, looks like Save-MSCatalogUpdate is broken 
![image](https://user-images.githubusercontent.com/9829838/166076740-213c42b1-8bf2-4e34-98eb-59f4d67a7b4a.png)

**Comment by jaromirk** [comment]
Looks like it's being fixed https://github.com/ryan-jan/MSCatalog/issues/14

**Comment by jaromirk** [comment]
Sorry for delay, I was waiting if someone will patch mscatalog itself. I added patch to the code - so it will fix the mscatalog you have on disk. Enjoy!
