### ISSUE TITLE
geeksoftware.pdf24creator outdated, will downgrade later versions

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#512]
in winget geeksoftware.pdf24creator is currently on 10.8.0 which is a very old version 

winget upgrade --all will detect this software and replace more recent version like 11.x to 10.8.0

request:
- please check why the winget repo bot does not detect new version of this software and update the YAMLs 

https://creator.pdf24.org/changelog/de.html

Thank you!

**Comment by jaromirk** [comment]
How is this related to MSLab? Am I missing something?
