### ISSUE TITLE
Execution Policy / Signing

### ISSUE THREAD

**Issue by FlorianHeigl** [microsoft/MSLab#513]
Please, could you somehow sign the scripts?
The whole powershell signing premise makes no sense if there's no way to run signed code from microsoft.
Opensource or not, isn't there some way?

**Comment by jaromirk** [comment]
@machv can we sign it?

**Comment by machv** [comment]
Work in progress :-) I have my own personal code signing certificate, but I would prefer to sign the scripts with a corporate one, I am investigating what would be the best way to proceed.


let's keep this one open.

**Comment by FlorianHeigl** [comment]
@machv bless you!

**Comment by FlorianHeigl** [comment]
You guys deserve hero hats for this!
Exemplary that you didn't chicken out but were helpful and worked with your
orgs processes to do the right thing!


Jaromir Kaspar ***@***.***> schrieb am Di., 29. Nov. 2022,
15:29:
