### ISSUE TITLE
Get-VM : Cannot validate argument on parameter 'Id'

### ISSUE THREAD

**Issue by TerenceFowler** [microsoft/MSLab#518]
I keep getting this error and I have not been able to figure out why, is there a step I am missing after running create parent disks? 

`Get-VM : Cannot validate argument on parameter 'Id'. The argument is null. Provide a valid value for the argument, and
then try running the command again.
At C:\HyperV\mslab_v22.07.1\3_Deploy.ps1:1597 char:34
                 $vm = Get-VM -Id $_.BaseName -ErrorAction SilentlyCon ...
                                  ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-VM], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.GetVM

Import-VM : Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not
null or empty, and then try the command again.
At C:\HyperV\mslab_v22.07.1\3_Deploy.ps1:1604 char:43
                     $DC = Import-VM -Path $_.FullName
                                          ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-VM], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.ImportVM

DC was not imported successfully Press any key to continue ...`

**Comment by jaromirk** [comment]
Sorry for late response. Can you check if DC VM exists under lab folder? 
![image](https://user-images.githubusercontent.com/9829838/189858076-7961ec86-6772-40c3-ae4f-0ec0f081af74.png)

**Comment by jaromirk** [comment]
Closing (no reply from Terence)
