### ISSUE TITLE
DownloadLatestCUs not working for Windows 10

### ISSUE THREAD

**Issue by razza-guhl** [microsoft/MSLab#520]
The script DownloadLatestCUs.ps1 does not work for OS Windows 10, no matter which release.

It seems the cmdlet "Get-MSCatalogUpdate" currently returns the ID for Windows 10 with 2x whitespaces between "Windows 10,  version" instead of 1x whitespace:

ID="Windows 10,  version 1903 and later" - (2x) current return
ID="Windows 10, version 1903 and later" - (1x) string used in script

After manuall changed the ID with 2x whitespaces in the script on lines 46 to 49, download of latest CU worked again.

PS: Sorry, I would make a pull request if I knew how to properly do that.

**Comment by jaromirk** [comment]
Thank you! Will take a look!

**Comment by jaromirk** [comment]
Fixed! I also added Win11 and fixed 21h2. THX!
