### ISSUE TITLE
Add try catch for stale / mounted WindowsImages

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#565]
In some cases deploy.ps1 or other scripts may fail because of an incorrectly mounted / dismounted or stale image.

This could be achieved before mounting a new image with Mount-WindowsImage, to check the condition 

`get-windowsimage -mounted`  is not $null

then execute

`dism /cleanup-mountpoints `

**Comment by Karl-WE** [comment]
In situation where scripts terminate because of errors or one does terminate because of human errors (wrong directory or labconfig) this would be still handy. 
Thanks for considering it for the next release and merging a change in dev branch. @machv @jaromirk

**Comment by jaromirk** [comment]
Hmm, I've never tried cleanup mount points. But what I know I had to move entire directory somewhere else as sometimes mountpoint was dirty and image was not be possible to mount even all was dismounted. The cleanup mount points works for this situation?

**Comment by Karl-WE** [comment]
Usually when still mounted one might not be able to rename or move the mountpoint. The command will remove the mountpoint and data. It is very similar in importance like removing mountpoints in Linux when you forgot to unmount an external disk.

how to repro:
run a regular mount / unmount command for a while
terminate this before completion
check for the folder 
run the cleanup 
check for the folder

**Comment by jaromirk** [comment]
added cleanup for stale images...
