### ISSUE TITLE
mslab 24.04 Hydration of DC fails after first reboot when Parent OS and VM (mslab DC) OS is Windows Server 2025

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#588]
The entire issue is described here
https://techcommunity.microsoft.com/t5/windows-server-insiders/b26085-windows-server-2025-domain-controller-fail-to-deploy-via/m-p/4119469

**Scenario:**
Host OS (Hyper-V): b26085 Windows Server 2025
Guest OS (DC): b26085 Windows Server 2025

**Issue:**
Application of DSC fails after the first reboot while hydrating the DC VM 

**Repro**
- Install WS 20**25** as host OS 
- Enable Hyper-V
- Deploy mslab 24.04
- Use WS 20**25** ISO during 2_createparentdisks.ps1

**Workaround:** 
Do not use WS 2025 as a guest VM OS at the moment, for CreateParentDisks (DC) until solved. 
Using WS 2025 for usual VMs, such as Management, WAC etc are not affected.

**Comment by Karl-WE** [comment]
This issue is under Investigation by Microsoft

**Comment by michbern-ms** [comment]
@jaromirk I put together a new 'NoDCHydrate' feature which enables one to work around this for now:
https://github.com/michbern-ms/MSLab/tree/user/michbern/dchydrate

Take a look and let me know if you want me to set up a PR.

The investigation on the OS side continues, but I wanted to offer the feature as a workaround.

**Comment by jaromirk** [comment]
Oh, that's sweet! @machv what do you think?

**Comment by Karl-WE** [comment]
related #596 #589

**Comment by Karl-WE** [comment]
Today, tested with Windows_InsiderPreview_Server_vNext_en-us_**26296**.iso. No change in behaviour. Waiting for fix.

**Comment by michbern-ms** [comment]
@Karl-WE That's unexpected.  Version 26296 has the two fixes necessary to resolve this scenario.   I ran the full scenario this morning with 26296, downloaded from the Preview center:
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver?msockid=1818fad5388d6a5b3e2ceef839376bbb

And it worked well.  I did not need to use the 'NoDehydrateDC' feature - it all just worked.

@jaromirk , @machv  - would it be possible for one of you to test with 26296 and see if you can reproduce what Karl is seeing?

**Comment by Karl-WE** [comment]
Hi @michbern-ms
Thanks for sharing this information. 

Hyper-V Host OS was the same build as the DC VM OS version.

I will try this again on Windows 11 24H2 as Hyper-V host OS.

**Comment by michbern-ms** [comment]
Very strange.  @jaromirk @machv Would love more data points if you can spare the time.

**Comment by Karl-WE** [comment]
It's killing me softly as I thought I could finally come back to a new lab and have fun.

I am eager to help Michael. As always.

**Comment by Karl-WE** [comment]
This issue is resolved with b26311. See also #607, #588

I am closing this with a **workaroud** remark:

> [!NOTE]
> for mslab DC creation please consider using 
> 1. mslab dev, as long there is no later mslab version than 26.04.1
> 2. use Windows Server ISO b26311 or later ISO for DC hydration in Step 2 (2_Createparentdisk.ps1) if you want to Test Windows Server 2025.
> As we can hopefully expect a backport from all related code changes b26311 back to b26100.1 + LCU this issue will be fully resolved.

fyi: @michbern-ms 
@jaromirk I would recommend linking this disclaimer to mslab and Dell GEOS to avoid "frustration" as people would not expect this and using b26100 instead. If you like I can write PRs for both areas.

Thank you everyone for their huge efforts!
