### ISSUE TITLE
mslab 24.04 - Importing hydrated DC VM fails to boot if the VM OS is WS 2025

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#589]
**Scenario:**
Host OS (Hyper-V): b26085 Windows Server 2022
Guest OS (DC): b26085 Windows Server 2025
mslab version: 24.04.01 - first noticed this in a 23.x release, appears to be related to WS 2025 changes.

**Issue:**
Using WS 2022 as host OS and WS 2025 for DC (2_CreateParentdisks.ps1). DC template can be created successfully.
When the hydrated DC is imported for a lab using 3_Deploy.ps1, the imported DC VM will fail to boot.

**Repro**
- Install WS 20**22** as host OS
- enable Hyper-V
- deploy mslab 24.04
- Use WS 20**25** ISO during 2_createparentdisks.ps1

**Workaround:**
Use WS 2022 as a guest OS

**Comment by Karl-WE** [comment]
This issue is under Investigation by Microsoft.

**Comment by Karl-WE** [comment]
related #596 #588

**Comment by michbern-ms** [comment]
There were two OS fixes that were made to address this issue, and both are present in build 26296.

I ran the full scenario this morning with 26296, downloaded from the Preview center:
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver?msockid=1818fad5388d6a5b3e2ceef839376bbb

I used a Server 2022 VM as a host, brought up to current patch level.

And it worked well. I did not need to use the 'NoDehydrateDC' feature - it all just worked.

**Comment by Karl-WE** [comment]
Thank you for testing Jaromir

Was this the hydrated DC VM ?
What's the OS version of the Hyper-V Host?

**Comment by jaromirk** [comment]
Yeah, in the screenshot it's DC. Host OS is ws2025. But I think imported dc did not work there, or did it?

**Comment by Karl-WE** [comment]
I see, the creation of the DC b26296 did not work (2_CreateParentDisks.ps1). Host OS is a b26296, too.
I will evaluate this situation with WS2022 / 2025 b26100 as host OS. Remote related also for the AzHCI 23H2 (3_Deploy).

**Comment by Karl-WE** [comment]
Can repro that the host OS plays a role.
Testing with WS 2022 as host OS there is no error with the DC. Michael has more details.
