### ISSUE TITLE
24.06.2 - 2_createParentDisks.ps1 fails in PowerShell 7

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#602]
Don't see why 

repro:
run Windows Server Insider b26296
install mslab 24.05.2
open Terminal > PowerShell 7.4.5
execute 1_Prereq
execute 2_CreateParentDisks

error:
`PS H:\mslab_v24.06.2-2408-prod> .\2_CreateParentDisks.ps1`

`ParserError: H:\mslab_v24.06.2-2408-prod\2_CreateParentDisks.ps1:1056
Line | 1056 |  …             Import-DscResource -ModuleName PSDesiredStateConfiguratio …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find the module 'PSDesiredStateConfiguration'.`

**Comment by Karl-WE** [comment]
doing the same Terminal > PS 5.1 works fine.

**Comment by Karl-WE** [comment]
can confirm this in a different OS (W11).

**Comment by Karl-WE** [comment]
Also confirm the same on WS 2022
Seems like it's related to PS 7.4.5.
@jaromirk can you repro this please
1_prereq and Tests are ok
2_createparentdisks fails

Using Windows Terminal / PS 7.4.5 fails
Using Windows Terminal / PS 5.1 works

Tested OS
WS Insider 
W11 24H2
WS 2022 

If you see the same I believe it might be good opening an issue in PowerShell 7 repo. I would care about this.

**Comment by jaromirk** [comment]
Yeah, it never worked with PS7

**Comment by Karl-WE** [comment]
Sad to hear. 1 and deploy and other Script work well.
OK I will open an issue in PowerShell github then.

**Comment by jaromirk** [comment]
Does not make sense. It's incompatible with PowerShell DSC. It's a "feature"

**Comment by Karl-WE** [comment]
OK. Thanks Jaromir. I have no insights so if you say they cannot fix this it's not worth trying. 

If I run createparentdisks from the subfolder there is no warning and termination 

Can I assume that only 2_createparentdisk is affected?

**Comment by michbern-ms** [comment]
Bug understood - this is a breaking change in PowerShell 7.2.   I went ahead and coded up a fix, please try it out.

https://github.com/microsoft/MSLab/pull/605

**Comment by jaromirk** [comment]
@michbern-ms i added you as admin. Feel free to discuss internally with @machv what's needed. Thank you for your contributions!

**Comment by michbern-ms** [comment]
Thanks, Jaromir - I'm honored.   I think my fix should cover the PS7 issue.  If there are other things we should look at together, please let me know.
